import { defineContent } from "@/content/define";

export const adminOperationsContentEntries = defineContent("admin", {
  "shell.cmsName": { value: "Trung tâm quản trị", description: "Tên khu vực quản trị." },
  "shell.cmsDescription": {
    value: "Soạn, kiểm tra và theo dõi nội dung",
    description: "Mô tả khu vực quản trị.",
  },
  "shell.openMenu": { value: "Mở menu quản trị", description: "Nhãn mở menu quản trị trên điện thoại." },
  "shell.closeMenu": { value: "Đóng menu quản trị", description: "Nhãn đóng menu quản trị trên điện thoại." },
  "shell.logout": { value: "Đăng xuất", description: "Nhãn đăng xuất khỏi khu vực quản trị." },
  "shell.workflowTitle": { value: "Quy trình nội dung an toàn", description: "Tiêu đề quy trình an toàn." },
  "shell.workflowDescription": {
    value: "Soạn nội dung, kiểm tra an toàn và được một người khác duyệt trước khi hiển thị cho trẻ.",
    description: "Mô tả quy trình an toàn.",
  },
  "navGroup.primary": { value: "Công việc chính", description: "Nhóm điều hướng công việc chính." },
  "navGroup.content": { value: "Soạn nội dung", description: "Nhóm điều hướng nội dung." },
  "navGroup.operations": { value: "Theo dõi hệ thống", description: "Nhóm điều hướng vận hành." },
  "nav.dashboard": { value: "Tổng quan", description: "Điều hướng tổng quan." },
  "nav.missions": { value: "Nhiệm vụ", description: "Điều hướng nhiệm vụ." },
  "nav.reviews": { value: "Duyệt nội dung", description: "Điều hướng kiểm duyệt." },
  "nav.media": { value: "Thư viện tư liệu", description: "Điều hướng thư viện tư liệu." },
  "nav.content": { value: "Câu chữ hiển thị", description: "Điều hướng nội dung giao diện." },
  "nav.worlds": { value: "Chủ đề nhiệm vụ", description: "Điều hướng thế giới nhiệm vụ." },
  "nav.taxonomy": { value: "Nhóm tuổi & kỹ năng", description: "Điều hướng độ tuổi và kỹ năng." },
  "nav.members": { value: "Thành viên & quyền", description: "Điều hướng thành viên." },
  "nav.reports": { value: "Tình hình sử dụng", description: "Điều hướng báo cáo." },
  "nav.dataRequests": { value: "Yêu cầu dữ liệu", description: "Điều hướng yêu cầu dữ liệu." },
  "nav.audit": { value: "Lịch sử thay đổi", description: "Điều hướng nhật ký thay đổi." },
  "nav.settings": { value: "Cấu hình hệ thống", description: "Điều hướng cài đặt nâng cao." },

  "taxonomy.ageTitle": { value: "Nhóm tuổi", description: "Tiêu đề quản lý nhóm tuổi." },
  "taxonomy.ageLabel": { value: "Tên nhóm tuổi", description: "Nhãn tên nhóm tuổi." },
  "taxonomy.ageDescription": { value: "Mô tả nhóm tuổi", description: "Nhãn mô tả nhóm tuổi." },
  "taxonomy.active": {
    value: "Cho phép sử dụng",
    description: "Nhãn bật hoặc tắt một nhóm tuổi hay kỹ năng.",
  },
  "taxonomy.save": { value: "Lưu thay đổi", description: "Nhãn lưu nhóm tuổi hoặc kỹ năng." },
  "taxonomy.saving": {
    value: "Đang lưu thay đổi...",
    description: "Trạng thái đang lưu nhóm tuổi hoặc kỹ năng.",
  },
  "taxonomy.ageSaved": { value: "Đã lưu nhóm tuổi", description: "Thông báo lưu nhóm tuổi." },
  "taxonomy.skillTitle": { value: "Kỹ năng và thói quen tích cực", description: "Tiêu đề quản lý kỹ năng." },
  "taxonomy.skillName": { value: "Tên kỹ năng", description: "Nhãn tên kỹ năng." },
  "taxonomy.skillDescription": { value: "Mô tả dễ hiểu", description: "Nhãn mô tả kỹ năng." },
  "taxonomy.skillCategory": { value: "Nhóm kỹ năng", description: "Nhãn phân nhóm kỹ năng." },
  "taxonomy.skillSaved": { value: "Đã lưu kỹ năng", description: "Thông báo lưu kỹ năng." },
  "taxonomy.createTitle": { value: "Thêm kỹ năng hoặc thói quen", description: "Tiêu đề thêm kỹ năng." },
  "taxonomy.create": { value: "Thêm kỹ năng", description: "Nhãn thêm kỹ năng." },
  "taxonomy.creating": { value: "Đang thêm...", description: "Trạng thái đang thêm kỹ năng." },
  "taxonomy.createSuccess": { value: "Đã thêm kỹ năng", description: "Thông báo thêm kỹ năng." },
  "review.commentLabel": { value: "Nhận xét cho người soạn", description: "Nhãn nhận xét kiểm duyệt." },
  "review.commentPlaceholder": {
    value: "Nêu rõ lý do duyệt hoặc nội dung cần chỉnh sửa...",
    description: "Placeholder nhận xét review.",
  },
  "review.approve": { value: "Nội dung đạt yêu cầu", description: "Nhãn duyệt nội dung." },
  "review.approving": { value: "Đang duyệt...", description: "Nhãn khi duyệt phiên bản." },
  "review.reject": { value: "Yêu cầu chỉnh sửa", description: "Nhãn từ chối phiên bản." },
  "review.rejecting": { value: "Đang trả lại...", description: "Nhãn khi trả lại phiên bản." },
  "review.approveSuccess": { value: "Đã duyệt phiên bản", description: "Thông báo duyệt phiên bản." },
  "review.rejectSuccess": { value: "Đã trả lại để chỉnh sửa", description: "Thông báo trả lại phiên bản." },
  "review.publish": { value: "Xuất bản ngay", description: "Nhãn xuất bản phiên bản." },
  "review.publishing": { value: "Đang xuất bản...", description: "Nhãn khi xuất bản." },
  "review.publishSuccess": {
    value: "Nhiệm vụ đã được hiển thị cho trẻ",
    description: "Thông báo xuất bản.",
  },
  "review.scheduleTitle": { value: "Hoặc lên lịch xuất bản", description: "Tiêu đề lên lịch xuất bản." },
  "review.schedule": { value: "Lưu lịch xuất bản", description: "Nhãn lưu lịch xuất bản." },
  "review.scheduling": { value: "Đang lên lịch...", description: "Nhãn khi lên lịch." },
  "review.scheduleSuccess": { value: "Đã lên lịch xuất bản", description: "Thông báo lên lịch." },
  "dashboard.eyebrow": { value: "Trung tâm công việc", description: "Nhãn đầu trang tổng quan." },
  "dashboard.title": { value: "Hôm nay cần làm gì?", description: "Tiêu đề trang tổng quan." },
  "dashboard.description": {
    value: "Bắt đầu từ các việc quan trọng, theo dõi nội dung đang soạn và kiểm tra những thay đổi gần đây.",
    description: "Mô tả trang tổng quan.",
  },
  "dashboard.priorityTitle": { value: "Việc ưu tiên", description: "Tiêu đề danh sách việc ưu tiên." },
  "dashboard.summaryTitle": { value: "Tình hình chung", description: "Tiêu đề số liệu tổng quan." },
  "dashboard.createMission": { value: "Tạo nhiệm vụ mới", description: "CTA tạo nhiệm vụ." },
  "dashboard.createMissionDescription": {
    value: "Bắt đầu từ mẫu và xem trước ngay khi soạn.",
    description: "Mô tả CTA tạo nhiệm vụ.",
  },
  "dashboard.draftTasks": { value: "bản nháp đang soạn", description: "CTA bản nháp." },
  "dashboard.draftTasksDescription": {
    value: "Tiếp tục nội dung còn dang dở hoặc cần chỉnh sửa.",
    description: "Mô tả CTA bản nháp.",
  },
  "dashboard.reviewTasks": { value: "nhiệm vụ chờ duyệt", description: "CTA kiểm duyệt." },
  "dashboard.reviewTasksDescription": {
    value: "Kiểm tra nội dung trước khi hiển thị cho trẻ.",
    description: "Mô tả CTA kiểm duyệt.",
  },
  "dashboard.mediaTasks": { value: "tư liệu cần kiểm tra", description: "CTA kiểm tra tư liệu." },
  "dashboard.mediaTasksDescription": {
    value: "Xác nhận hình ảnh và âm thanh phù hợp.",
    description: "Mô tả CTA kiểm tra tư liệu.",
  },
  "dashboard.mediaLibrary": { value: "Quản lý hình ảnh & âm thanh", description: "CTA thư viện tư liệu." },
  "dashboard.mediaLibraryDescription": {
    value: "Tải lên và sắp xếp tư liệu dùng trong nhiệm vụ.",
    description: "Mô tả CTA thư viện tư liệu.",
  },
  "dashboard.viewReports": { value: "Xem báo cáo 30 ngày", description: "CTA báo cáo." },
  "dashboard.viewReportsDescription": {
    value: "Theo dõi lượt chơi, độ chính xác và nội dung nổi bật.",
    description: "Mô tả CTA báo cáo.",
  },
  "dashboard.contentStatus": { value: "Tiến độ nội dung", description: "Tiêu đề tiến độ nội dung." },
  "dashboard.openCms": { value: "Xem tất cả nhiệm vụ", description: "CTA mở danh sách nhiệm vụ." },
  "dashboard.emptyMissions": { value: "Chưa có nhiệm vụ nào.", description: "Trạng thái nhiệm vụ trống." },
  "dashboard.recentAudit": { value: "Thay đổi gần đây", description: "Tiêu đề thay đổi gần đây." },
  "dashboard.viewAudit": { value: "Xem nhật ký thay đổi", description: "CTA xem nhật ký." },
  "missions.eyebrow": { value: "Kho nội dung", description: "Nhãn đầu danh sách nhiệm vụ." },
  "missions.title": { value: "Quản lý nhiệm vụ", description: "Tiêu đề danh sách nhiệm vụ." },
  "missions.description": {
    value: "Tạo, chỉnh sửa và theo dõi từng nhiệm vụ từ bản nháp đến khi hiển thị cho trẻ.",
    description: "Mô tả danh sách nhiệm vụ cho biên tập viên.",
  },
  "missions.readOnlyDescription": {
    value: "Xem toàn bộ nhiệm vụ và trạng thái hiện tại; nội dung chờ duyệt nằm trong mục Duyệt nội dung.",
    description: "Mô tả danh sách nhiệm vụ cho người kiểm duyệt.",
  },
  "missions.create": { value: "Tạo nhiệm vụ mới", description: "CTA tạo nhiệm vụ." },
  "missions.search": { value: "Tìm theo tên nhiệm vụ", description: "Placeholder tìm nhiệm vụ." },
  "missions.allWorlds": { value: "Mọi thế giới", description: "Bộ lọc mọi thế giới." },
  "missions.allStatuses": { value: "Mọi trạng thái", description: "Bộ lọc mọi trạng thái." },
  "missions.filter": { value: "Áp dụng", description: "Nhãn áp dụng bộ lọc." },
  "missions.resultCount": { value: "{count} nhiệm vụ", description: "Số kết quả nhiệm vụ." },
  "missions.columnMission": { value: "Nhiệm vụ", description: "Cột Mission." },
  "missions.columnWorld": { value: "Thế giới", description: "Cột Mission World." },
  "missions.columnStatus": { value: "Trạng thái", description: "Cột trạng thái." },
  "missions.columnContent": { value: "Độ dài", description: "Cột độ dài nhiệm vụ." },
  "missions.columnUpdated": { value: "Cập nhật", description: "Cột thời gian cập nhật." },
  "missions.columnActions": { value: "Thao tác", description: "Cột thao tác." },
  "missions.summary": {
    value: "{questions} câu hỏi · khoảng {minutes} phút",
    description: "Tóm tắt độ dài nhiệm vụ.",
  },
  "missions.empty": { value: "Không có nhiệm vụ phù hợp.", description: "Trạng thái Mission List trống." },
  "missions.status.draft": { value: "Bản nháp", description: "Nhãn trạng thái draft." },
  "missions.status.in_review": { value: "Chờ duyệt", description: "Nhãn trạng thái in review." },
  "missions.status.rejected": { value: "Cần sửa", description: "Nhãn trạng thái rejected." },
  "missions.status.approved": { value: "Đã duyệt", description: "Nhãn trạng thái approved." },
  "missions.status.published": { value: "Đã xuất bản", description: "Nhãn trạng thái published." },
  "missions.status.archived": { value: "Lưu trữ", description: "Nhãn trạng thái archived." },
  "reviews.eyebrow": { value: "Kiểm tra nội dung", description: "Nhãn đầu danh sách kiểm duyệt." },
  "reviews.title": { value: "Danh sách chờ kiểm duyệt", description: "Tiêu đề danh sách kiểm duyệt." },
  "reviews.description": {
    value:
      "Mở từng nhiệm vụ để xem như trẻ sẽ thấy, kiểm tra an toàn rồi duyệt hoặc ghi rõ phần cần chỉnh sửa.",
    description: "Mô tả danh sách kiểm duyệt.",
  },
  "reviews.version": { value: "Lần gửi {number}", description: "Nhãn lần gửi kiểm duyệt." },
  "reviews.submittedAt": { value: "Được gửi lúc {time}", description: "Thời điểm gửi kiểm duyệt." },
  "reviews.empty": {
    value: "Không có nhiệm vụ nào đang chờ kiểm duyệt.",
    description: "Danh sách kiểm duyệt trống.",
  },
});
