import { defineContent } from "@/content/define";

export const adminOperationsContentEntries = defineContent("admin", {
  "shell.cmsName": { value: "Suy Luận Nhí CMS", description: "Tên CMS." },
  "shell.cmsDescription": { value: "Quản trị nội dung an toàn", description: "Mô tả CMS." },
  "shell.openMenu": { value: "Mở menu quản trị", description: "Nhãn mở menu CMS mobile." },
  "shell.closeMenu": { value: "Đóng menu quản trị", description: "Nhãn đóng menu CMS mobile." },
  "shell.logout": { value: "Đăng xuất", description: "Nhãn đăng xuất CMS." },
  "shell.workflowTitle": { value: "Child-safe workflow", description: "Tiêu đề workflow an toàn." },
  "shell.workflowDescription": {
    value: "Draft không thay đổi phiên bản đã publish. Reviewer phải duyệt trước khi xuất bản.",
    description: "Mô tả workflow an toàn.",
  },
  "nav.dashboard": { value: "Tổng quan", description: "Điều hướng tổng quan CMS." },
  "nav.missions": { value: "Nhiệm vụ", description: "Điều hướng Mission CMS." },
  "nav.reviews": { value: "Kiểm duyệt", description: "Điều hướng review." },
  "nav.media": { value: "Media", description: "Điều hướng media." },
  "nav.content": { value: "Nội dung hệ thống", description: "Điều hướng content registry." },
  "nav.worlds": { value: "Thế giới", description: "Điều hướng Mission Worlds." },
  "nav.taxonomy": { value: "Độ tuổi & kỹ năng", description: "Điều hướng taxonomy." },
  "nav.members": { value: "Thành viên", description: "Điều hướng thành viên." },
  "nav.reports": { value: "Báo cáo", description: "Điều hướng báo cáo." },
  "nav.dataRequests": { value: "Data requests", description: "Điều hướng data requests." },
  "nav.audit": { value: "Audit log", description: "Điều hướng audit." },
  "nav.settings": { value: "Cài đặt", description: "Điều hướng system settings." },

  "taxonomy.ageTitle": { value: "Nhóm tuổi", description: "Tiêu đề quản lý nhóm tuổi." },
  "taxonomy.ageLabel": { value: "Tên nhóm tuổi", description: "Nhãn tên nhóm tuổi." },
  "taxonomy.ageDescription": { value: "Mô tả nhóm tuổi", description: "Nhãn mô tả nhóm tuổi." },
  "taxonomy.active": { value: "Đang sử dụng", description: "Nhãn active taxonomy." },
  "taxonomy.save": { value: "Lưu", description: "Nhãn lưu taxonomy." },
  "taxonomy.saving": { value: "Đang lưu...", description: "Nhãn khi lưu taxonomy." },
  "taxonomy.ageSaved": { value: "Đã lưu nhóm tuổi", description: "Thông báo lưu nhóm tuổi." },
  "taxonomy.skillTitle": { value: "Kỹ năng & Thinking Habits", description: "Tiêu đề quản lý kỹ năng." },
  "taxonomy.skillName": { value: "Tên kỹ năng", description: "Nhãn tên kỹ năng." },
  "taxonomy.skillDescription": { value: "Mô tả", description: "Nhãn mô tả kỹ năng." },
  "taxonomy.skillCategory": { value: "Danh mục", description: "Nhãn danh mục kỹ năng." },
  "taxonomy.skillSaved": { value: "Đã lưu kỹ năng", description: "Thông báo lưu kỹ năng." },
  "taxonomy.createTitle": { value: "Tạo kỹ năng mới", description: "Tiêu đề tạo kỹ năng." },
  "taxonomy.create": { value: "Tạo", description: "Nhãn tạo kỹ năng." },
  "taxonomy.creating": { value: "Đang tạo...", description: "Nhãn khi tạo kỹ năng." },
  "taxonomy.createSuccess": { value: "Đã tạo kỹ năng", description: "Thông báo tạo kỹ năng." },
  "review.commentLabel": { value: "Nhận xét reviewer", description: "Nhãn nhận xét review." },
  "review.commentPlaceholder": {
    value: "Nêu rõ lý do duyệt hoặc nội dung cần chỉnh sửa...",
    description: "Placeholder nhận xét review.",
  },
  "review.approve": { value: "Duyệt phiên bản", description: "Nhãn duyệt phiên bản." },
  "review.approving": { value: "Đang duyệt...", description: "Nhãn khi duyệt phiên bản." },
  "review.reject": { value: "Yêu cầu chỉnh sửa", description: "Nhãn từ chối phiên bản." },
  "review.rejecting": { value: "Đang trả lại...", description: "Nhãn khi trả lại phiên bản." },
  "review.approveSuccess": { value: "Đã duyệt phiên bản", description: "Thông báo duyệt phiên bản." },
  "review.rejectSuccess": { value: "Đã trả lại để chỉnh sửa", description: "Thông báo trả lại phiên bản." },
  "review.publish": { value: "Xuất bản ngay", description: "Nhãn xuất bản phiên bản." },
  "review.publishing": { value: "Đang xuất bản...", description: "Nhãn khi xuất bản." },
  "review.publishSuccess": {
    value: "Phiên bản đã được xuất bản cho Child App",
    description: "Thông báo xuất bản.",
  },
  "review.scheduleTitle": { value: "Hoặc lên lịch xuất bản", description: "Tiêu đề lên lịch xuất bản." },
  "review.schedule": { value: "Lưu lịch xuất bản", description: "Nhãn lưu lịch xuất bản." },
  "review.scheduling": { value: "Đang lên lịch...", description: "Nhãn khi lên lịch." },
  "review.scheduleSuccess": { value: "Đã lên lịch xuất bản", description: "Thông báo lên lịch." },
  "dashboard.eyebrow": { value: "Operational overview", description: "Nhãn đầu Admin Dashboard." },
  "dashboard.title": { value: "Tổng quan hệ thống", description: "Tiêu đề Admin Dashboard." },
  "dashboard.accounts": { value: "Tài khoản", description: "Metric tổng tài khoản." },
  "dashboard.children": { value: "Hồ sơ bé", description: "Metric tổng Child Profile." },
  "dashboard.sessions30d": { value: "Phiên chơi 30 ngày", description: "Metric session 30 ngày." },
  "dashboard.pendingReviews": { value: "Chờ duyệt", description: "Metric phiên bản chờ duyệt." },
  "dashboard.pendingMedia": { value: "Media chờ duyệt", description: "Metric media chờ duyệt." },
  "dashboard.contentStatus": { value: "Trạng thái nội dung", description: "Tiêu đề trạng thái content." },
  "dashboard.openCms": { value: "Mở CMS", description: "CTA mở Mission CMS." },
  "dashboard.emptyMissions": { value: "Chưa có dữ liệu nhiệm vụ.", description: "Trạng thái Mission trống." },
  "dashboard.recentAudit": { value: "Audit gần đây", description: "Tiêu đề audit gần đây." },
  "dashboard.viewAudit": { value: "Xem toàn bộ audit log", description: "CTA xem audit log." },
  "missions.eyebrow": { value: "Content operations", description: "Nhãn đầu Mission List." },
  "missions.title": { value: "Danh sách nhiệm vụ", description: "Tiêu đề Mission List." },
  "missions.create": { value: "Tạo nhiệm vụ", description: "CTA tạo Mission." },
  "missions.search": { value: "Tìm tên hoặc slug", description: "Placeholder tìm Mission." },
  "missions.allWorlds": { value: "Tất cả thế giới", description: "Bộ lọc mọi Mission World." },
  "missions.allStatuses": { value: "Tất cả trạng thái", description: "Bộ lọc mọi trạng thái Mission." },
  "missions.filter": { value: "Lọc", description: "Nhãn lọc Mission List." },
  "missions.columnMission": { value: "Nhiệm vụ", description: "Cột Mission." },
  "missions.columnWorld": { value: "Thế giới", description: "Cột Mission World." },
  "missions.columnStatus": { value: "Trạng thái", description: "Cột trạng thái." },
  "missions.columnContent": { value: "Nội dung", description: "Cột thông tin content." },
  "missions.columnUpdated": { value: "Cập nhật", description: "Cột thời gian cập nhật." },
  "missions.columnActions": { value: "Thao tác", description: "Cột thao tác." },
  "missions.summary": { value: "{questions} câu · {minutes} phút", description: "Tóm tắt độ dài Mission." },
  "missions.empty": { value: "Không có nhiệm vụ phù hợp.", description: "Trạng thái Mission List trống." },
  "missions.status.draft": { value: "Bản nháp", description: "Nhãn trạng thái draft." },
  "missions.status.in_review": { value: "Chờ duyệt", description: "Nhãn trạng thái in review." },
  "missions.status.rejected": { value: "Cần sửa", description: "Nhãn trạng thái rejected." },
  "missions.status.approved": { value: "Đã duyệt", description: "Nhãn trạng thái approved." },
  "missions.status.published": { value: "Đã xuất bản", description: "Nhãn trạng thái published." },
  "missions.status.archived": { value: "Lưu trữ", description: "Nhãn trạng thái archived." },
  "reviews.eyebrow": { value: "Review queue", description: "Nhãn đầu Review Queue." },
  "reviews.title": { value: "Nhiệm vụ chờ duyệt", description: "Tiêu đề Review Queue." },
  "reviews.version": { value: "Version {number}", description: "Nhãn version chờ review." },
  "reviews.submittedAt": { value: "Gửi lúc {time}", description: "Thời điểm gửi review." },
  "reviews.empty": { value: "Không có nhiệm vụ đang chờ duyệt.", description: "Review Queue trống." },
});
