import { defineContent } from "@/content/define";

export const adminOperationsContentEntries = defineContent("admin", {
  "shell.cmsName": { value: "Khu vực quản trị", description: "Tên khu vực quản trị." },
  "shell.cmsDescription": {
    value: "Soạn nội dung, kiểm tra và theo dõi hoạt động",
    description: "Mô tả khu vực quản trị.",
  },
  "shell.openMenu": { value: "Mở menu quản trị", description: "Nhãn mở menu quản trị trên điện thoại." },
  "shell.closeMenu": { value: "Đóng menu quản trị", description: "Nhãn đóng menu quản trị trên điện thoại." },
  "shell.logout": { value: "Đăng xuất", description: "Nhãn đăng xuất khỏi khu vực quản trị." },
  "shell.mainContent": { value: "Nội dung quản trị", description: "Nhãn vùng nội dung cuộn quản trị." },
  "shell.workflowTitle": {
    value: "Các bước trước khi cho bé xem",
    description: "Tiêu đề quy trình an toàn.",
  },
  "shell.workflowDescription": {
    value: "Soạn nội dung, kiểm tra độ an toàn, rồi nhờ một người khác xem lại trước khi cho bé sử dụng.",
    description: "Mô tả quy trình an toàn.",
  },
  "navGroup.primary": { value: "Việc cần làm", description: "Nhóm điều hướng công việc chính." },
  "navGroup.content": { value: "Nội dung trong ứng dụng", description: "Nhóm điều hướng nội dung." },
  "navGroup.operations": { value: "Quản lý và theo dõi", description: "Nhóm điều hướng vận hành." },
  "nav.dashboard": { value: "Tổng quan", description: "Điều hướng tổng quan." },
  "nav.parentArea": {
    value: "Khu vực phụ huynh",
    description: "Lối tắt dành cho quản trị viên mở khu vực phụ huynh.",
  },
  "nav.missions": { value: "Nhiệm vụ", description: "Điều hướng nhiệm vụ." },
  "nav.reviews": { value: "Nội dung chờ kiểm tra", description: "Điều hướng kiểm tra nội dung." },
  "nav.media": { value: "Hình ảnh và âm thanh", description: "Điều hướng thư viện tệp." },
  "nav.content": {
    value: "Nội dung hiển thị",
    description: "Điều hướng đến phần quản lý nội dung hiển thị trong ứng dụng.",
  },
  "nav.contentVariables": {
    value: "Thông tin tự điền",
    description: "Điều hướng đến phần quản lý thông tin được tự điền vào nội dung dành cho Super Admin.",
  },
  "nav.worlds": { value: "Các chủ đề", description: "Điều hướng thế giới nhiệm vụ." },
  "nav.badges": { value: "Huy hiệu", description: "Điều hướng quản lý huy hiệu phần thưởng." },
  "nav.taxonomy": { value: "Nhóm tuổi & kỹ năng", description: "Điều hướng độ tuổi và kỹ năng." },
  "nav.members": { value: "Tài khoản quản trị", description: "Điều hướng thành viên." },
  "nav.feedback": { value: "Góp ý hệ thống", description: "Điều hướng góp ý từ người dùng." },
  "nav.reports": { value: "Báo cáo sử dụng", description: "Điều hướng báo cáo." },
  "nav.dataRequests": { value: "Xuất và xóa dữ liệu", description: "Điều hướng yêu cầu dữ liệu." },
  "nav.audit": { value: "Ai đã thay đổi gì", description: "Điều hướng nhật ký thay đổi." },
  "nav.settings": { value: "Cấu hình hệ thống", description: "Điều hướng cấu hình vận hành hệ thống." },

  "taxonomy.ageTitle": { value: "Nhóm tuổi", description: "Tiêu đề quản lý nhóm tuổi." },
  "taxonomy.ageLabel": { value: "Tên nhóm tuổi", description: "Nhãn tên nhóm tuổi." },
  "taxonomy.ageDescription": { value: "Mô tả nhóm tuổi", description: "Nhãn mô tả nhóm tuổi." },
  "taxonomy.active": {
    value: "Đang sử dụng",
    description: "Nhãn bật hoặc tắt một nhóm tuổi hay kỹ năng.",
  },
  "taxonomy.save": { value: "Lưu thay đổi", description: "Nhãn lưu nhóm tuổi hoặc kỹ năng." },
  "taxonomy.saving": {
    value: "Đang lưu thay đổi...",
    description: "Trạng thái đang lưu nhóm tuổi hoặc kỹ năng.",
  },
  "taxonomy.ageSaved": { value: "Đã lưu nhóm tuổi", description: "Thông báo lưu nhóm tuổi." },
  "taxonomy.skillTitle": { value: "Kỹ năng bé sẽ luyện", description: "Tiêu đề quản lý kỹ năng." },
  "taxonomy.skillName": { value: "Tên kỹ năng", description: "Nhãn tên kỹ năng." },
  "taxonomy.skillDescription": { value: "Mô tả dễ hiểu", description: "Nhãn mô tả kỹ năng." },
  "taxonomy.skillCategory": { value: "Loại kỹ năng", description: "Nhãn phân nhóm kỹ năng." },
  "taxonomy.skillSaved": { value: "Đã lưu kỹ năng", description: "Thông báo lưu kỹ năng." },
  "taxonomy.createTitle": { value: "Thêm kỹ năng hoặc thói quen", description: "Tiêu đề thêm kỹ năng." },
  "taxonomy.create": { value: "Thêm kỹ năng", description: "Nhãn thêm kỹ năng." },
  "taxonomy.creating": { value: "Đang thêm...", description: "Trạng thái đang thêm kỹ năng." },
  "taxonomy.createSuccess": { value: "Đã thêm kỹ năng", description: "Thông báo thêm kỹ năng." },
  "review.commentLabel": {
    value: "Lời nhắn cho người soạn",
    description: "Nhãn nhận xét kiểm tra nội dung.",
  },
  "review.commentDescription": {
    value: "Có thể để trống khi nội dung đã ổn. Nếu cần sửa, hãy ghi rõ phần nào và nên sửa thế nào.",
    description: "Giải thích khi nào nhận xét kiểm tra nội dung là bắt buộc.",
  },
  "review.commentPlaceholder": {
    value: "Nêu rõ phần cần sửa và cách sửa mong muốn...",
    description: "Gợi ý trong ô nhập nhận xét review.",
  },
  "review.approve": { value: "Đạt yêu cầu", description: "Nhãn duyệt nội dung." },
  "review.approving": { value: "Đang xác nhận...", description: "Nhãn khi duyệt lần gửi." },
  "review.reject": { value: "Gửi lại để sửa", description: "Nhãn từ chối lần gửi." },
  "review.rejecting": { value: "Đang trả lại...", description: "Nhãn khi trả lại lần gửi." },
  "review.approveSuccess": {
    value: "Đã xác nhận nội dung đạt yêu cầu",
    description: "Thông báo duyệt lần gửi.",
  },
  "review.rejectSuccess": { value: "Đã trả lại để chỉnh sửa", description: "Thông báo trả lại lần gửi." },
  "review.publish": { value: "Cho bé xem ngay", description: "Nhãn hiển thị lần gửi." },
  "review.publishing": { value: "Đang đưa nội dung lên...", description: "Nhãn khi hiển thị." },
  "review.publishSuccessTitle": {
    value: "Đã cho bé xem",
    description: "Tiêu đề thông báo hiển thị thành công.",
  },
  "review.publishSuccess": {
    value: "Nhiệm vụ đã xuất hiện trong khu vực của bé",
    description: "Chi tiết thông báo hiển thị.",
  },
  "review.scheduleTitle": {
    value: "Hoặc chọn thời gian hiển thị",
    description: "Tiêu đề lên lịch hiển thị.",
  },
  "review.schedule": { value: "Lưu thời gian hiển thị", description: "Nhãn lưu lịch hiển thị." },
  "review.scheduling": { value: "Đang lưu thời gian...", description: "Nhãn khi lên lịch." },
  "review.scheduleSuccessTitle": {
    value: "Đã lưu thời gian hiển thị",
    description: "Tiêu đề thông báo lưu lịch hiển thị.",
  },
  "review.scheduleSuccess": {
    value: "Nhiệm vụ sẽ tự động xuất hiện cho bé vào thời gian đã chọn",
    description: "Chi tiết thông báo lên lịch.",
  },
  "dashboard.eyebrow": { value: "Tổng quan hôm nay", description: "Nhãn đầu trang tổng quan." },
  "dashboard.title": { value: "Hôm nay cần làm gì?", description: "Tiêu đề trang tổng quan." },
  "dashboard.description": {
    value: "Bắt đầu từ các việc quan trọng, theo dõi nội dung đang soạn và kiểm tra những thay đổi gần đây.",
    description: "Mô tả trang tổng quan.",
  },
  "dashboard.priorityTitle": { value: "Việc nên làm trước", description: "Tiêu đề danh sách việc ưu tiên." },
  "dashboard.summaryTitle": { value: "Tình hình nội dung", description: "Tiêu đề số liệu tổng quan." },
  "dashboard.createMission": { value: "Tạo nhiệm vụ mới", description: "lối tắt tạo nhiệm vụ." },
  "dashboard.createMissionDescription": {
    value: "Bắt đầu từ mẫu và xem trước ngay khi soạn.",
    description: "Mô tả lối tắt tạo nhiệm vụ.",
  },
  "dashboard.draftTasks": { value: "bản nháp cần làm tiếp", description: "lối tắt bản nháp." },
  "dashboard.draftTasksDescription": {
    value: "Tiếp tục nội dung còn dang dở hoặc cần chỉnh sửa.",
    description: "Mô tả lối tắt bản nháp.",
  },
  "dashboard.reviewTasks": { value: "nhiệm vụ đang chờ kiểm tra", description: "lối tắt kiểm tra nội dung." },
  "dashboard.reviewTasksDescription": {
    value: "Kiểm tra nội dung trước khi cho bé xem.",
    description: "Mô tả lối tắt kiểm tra nội dung.",
  },
  "dashboard.mediaTasks": { value: "hình ảnh, âm thanh cần kiểm tra", description: "lối tắt kiểm tra tệp." },
  "dashboard.mediaTasksDescription": {
    value: "Xác nhận hình ảnh và âm thanh phù hợp.",
    description: "Mô tả lối tắt kiểm tra tệp.",
  },
  "dashboard.mediaLibrary": { value: "Quản lý hình ảnh & âm thanh", description: "lối tắt thư viện tệp." },
  "dashboard.mediaLibraryDescription": {
    value: "Thêm và sắp xếp hình ảnh, âm thanh hoặc video dùng trong nhiệm vụ.",
    description: "Mô tả lối tắt thư viện tệp.",
  },
  "dashboard.viewReports": { value: "Xem báo cáo 30 ngày", description: "lối tắt báo cáo." },
  "dashboard.viewReportsDescription": {
    value: "Theo dõi lượt chơi, độ chính xác và nội dung nổi bật.",
    description: "Mô tả lối tắt báo cáo.",
  },
  "dashboard.contentStatus": {
    value: "Các nhiệm vụ đang ở bước nào",
    description: "Tiêu đề tiến độ nội dung.",
  },
  "dashboard.openCms": { value: "Xem tất cả nhiệm vụ", description: "lối tắt mở danh sách nhiệm vụ." },
  "dashboard.emptyMissions": { value: "Chưa có nhiệm vụ nào.", description: "Trạng thái nhiệm vụ trống." },
  "dashboard.recentAudit": { value: "Thay đổi mới nhất", description: "Tiêu đề thay đổi gần đây." },
  "dashboard.viewAudit": { value: "Xem ai đã thay đổi gì", description: "lối tắt xem nhật ký." },
  "missions.eyebrow": { value: "Danh sách nội dung", description: "Nhãn đầu danh sách nhiệm vụ." },
  "missions.title": { value: "Danh sách nhiệm vụ", description: "Tiêu đề danh sách nhiệm vụ." },
  "missions.description": {
    value: "Tạo, chỉnh sửa và theo dõi từng nhiệm vụ từ bản nháp đến khi cho bé xem.",
    description: "Mô tả danh sách nhiệm vụ cho biên tập viên.",
  },
  "missions.readOnlyDescription": {
    value:
      "Bạn có thể xem toàn bộ nhiệm vụ và trạng thái hiện tại. Nhiệm vụ đang chờ kiểm tra nằm trong mục Nội dung chờ kiểm tra.",
    description: "Mô tả danh sách nhiệm vụ cho người kiểm tra nội dung.",
  },
  "missions.create": { value: "Tạo nhiệm vụ mới", description: "lối tắt tạo nhiệm vụ." },
  "missions.search": { value: "Tìm tên nhiệm vụ", description: "Gợi ý trong ô nhập tìm nhiệm vụ." },
  "missions.allWorlds": { value: "Tất cả chủ đề", description: "Bộ lọc mọi thế giới." },
  "missions.allStatuses": {
    value: "Mọi trạng thái đang quản lý",
    description: "Bộ lọc các trạng thái chưa lưu trữ.",
  },
  "missions.filter": { value: "Lọc", description: "Nhãn áp dụng bộ lọc." },
  "missions.resultCount": { value: "{count} nhiệm vụ", description: "Số kết quả nhiệm vụ." },
  "missions.archiveResultCount": {
    value: "{count} nhiệm vụ trong Kho lưu trữ",
    description: "Số nhiệm vụ đã lưu trữ.",
  },
  "missions.columnMission": { value: "Nhiệm vụ", description: "Cột nhiệm vụ." },
  "missions.columnWorld": { value: "Chủ đề", description: "Cột nhiệm vụ World." },
  "missions.columnStatus": { value: "Trạng thái", description: "Cột trạng thái." },
  "missions.columnContent": { value: "Số câu và thời gian", description: "Cột độ dài nhiệm vụ." },
  "missions.columnUpdated": { value: "Sửa gần nhất", description: "Cột thời gian cập nhật." },
  "missions.columnTimeline": { value: "Thời gian", description: "Cột thời gian cập nhật hoặc lưu trữ." },
  "missions.columnActions": { value: "Thao tác", description: "Cột thao tác." },
  "missions.summary": {
    value: "{questions} câu hỏi · khoảng {minutes} phút",
    description: "Tóm tắt độ dài nhiệm vụ.",
  },
  "missions.empty": { value: "Không có nhiệm vụ phù hợp.", description: "Trạng thái nhiệm vụ List trống." },
  "missions.archiveEmpty": { value: "Kho lưu trữ đang trống.", description: "Trạng thái Kho lưu trữ trống." },
  "missions.status.draft": { value: "Bản nháp", description: "Nhãn trạng thái draft." },
  "missions.status.in_review": { value: "Chờ kiểm tra", description: "Nhãn trạng thái in review." },
  "missions.status.rejected": { value: "Cần sửa", description: "Nhãn trạng thái rejected." },
  "missions.status.approved": { value: "Đạt yêu cầu", description: "Nhãn trạng thái approved." },
  "missions.status.published": { value: "Đang hiển thị", description: "Nhãn trạng thái đang hiển thị." },
  "missions.status.archived": { value: "Đã lưu trữ", description: "Nhãn trạng thái archived." },
  "reviews.eyebrow": { value: "Kiểm tra nội dung", description: "Nhãn đầu danh sách kiểm tra nội dung." },
  "reviews.title": {
    value: "Duyệt và hiển thị nội dung",
    description: "Tiêu đề khu vực duyệt và hiển thị nội dung.",
  },
  "reviews.description": {
    value: "Kiểm tra nội dung mới gửi, sau đó tiếp tục đưa các nhiệm vụ đã đạt yêu cầu đến với bé.",
    description: "Mô tả khu vực duyệt và hiển thị nội dung.",
  },
  "reviews.pendingTitle": { value: "Chờ kiểm tra", description: "Tiêu đề nhóm đang chờ kiểm tra." },
  "reviews.pendingDescription": {
    value: "Xem nội dung như bé sẽ thấy, kiểm tra độ an toàn rồi xác nhận hoặc ghi rõ phần cần sửa.",
    description: "Mô tả nhóm đang chờ kiểm tra.",
  },
  "reviews.pendingStatus": { value: "Chờ kiểm tra", description: "Trạng thái đang chờ kiểm tra." },
  "reviews.approvedTitle": {
    value: "Đã duyệt, chờ hiển thị",
    description: "Tiêu đề nhóm đã duyệt nhưng chưa hiển thị.",
  },
  "reviews.approvedDescription": {
    value: "Các nhiệm vụ đã đạt yêu cầu nhưng chưa được đưa đến khu vực của bé.",
    description: "Mô tả nhóm đã duyệt nhưng chưa hiển thị.",
  },
  "reviews.approvedStatus": { value: "Đã duyệt", description: "Trạng thái nội dung đã duyệt." },
  "reviews.version": { value: "Lần gửi {number}", description: "Nhãn lần gửi kiểm tra nội dung." },
  "reviews.submittedAt": { value: "Gửi lúc {time}", description: "Thời điểm gửi kiểm tra nội dung." },
  "reviews.reviewedAt": { value: "Duyệt lúc {time}", description: "Thời điểm nội dung được duyệt." },
  "reviews.scheduledFor": {
    value: "Đã hẹn hiển thị lúc {time}",
    description: "Thời điểm nội dung được hẹn hiển thị.",
  },
  "reviews.openReview": { value: "Mở để kiểm tra", description: "Thao tác mở nội dung chờ kiểm tra." },
  "reviews.openApproved": {
    value: "Mở để hiển thị",
    description: "Thao tác mở nội dung đã duyệt để hiển thị.",
  },
  "reviews.empty": {
    value: "Hiện không có nhiệm vụ nào cần kiểm tra.",
    description: "Danh sách kiểm tra nội dung trống.",
  },
  "reviews.approvedEmpty": {
    value: "Hiện không có nhiệm vụ nào đang chờ hiển thị.",
    description: "Danh sách nội dung đã duyệt đang trống.",
  },
});
