import { defineContent } from "@/content/define";

export const profileContentEntries = defineContent("profile", {
  "create.nameLabel": { value: "Tên thân mật của bé", description: "Nhãn tên hồ sơ bé." },
  "create.nameDescription": { value: "Không cần dùng tên thật đâu nhé.", description: "Gợi ý tên hồ sơ bé." },
  "create.namePlaceholder": { value: "Ví dụ: Bống, Mít...", description: "Placeholder tên thân mật của bé." },
  "create.ageLabel": { value: "Bé thuộc nhóm tuổi nào?", description: "Nhãn chọn nhóm tuổi." },
  "create.ageDescription": {
    value: "Để Bống chọn nhiệm vụ vừa sức nhất.",
    description: "Mô tả chọn nhóm tuổi.",
  },
  "create.age.2-3.title": { value: "2–3 tuổi", description: "Tên nhóm tuổi 2–3." },
  "create.age.2-3.note": { value: "Nhận biết và ghép đôi", description: "Mô tả nhóm tuổi 2–3." },
  "create.age.4-5.title": { value: "4–5 tuổi", description: "Tên nhóm tuổi 4–5." },
  "create.age.4-5.note": { value: "Quy luật đơn giản", description: "Mô tả nhóm tuổi 4–5." },
  "create.age.6-8.title": { value: "6–8 tuổi", description: "Tên nhóm tuổi 6–8." },
  "create.age.6-8.note": { value: "Suy luận và so sánh", description: "Mô tả nhóm tuổi 6–8." },
  "create.privacyTitle": { value: "Chỉ thu thập điều thật sự cần", description: "Tiêu đề cam kết riêng tư." },
  "create.privacyDescription": {
    value: "Không email của bé, không ngày sinh đầy đủ, không quảng cáo và không mua hàng.",
    description: "Mô tả cam kết riêng tư.",
  },
  "create.submit": { value: "Bắt đầu chế độ bé →", description: "Nhãn nút tạo hồ sơ." },
  "create.submitting": { value: "Đang tạo hồ sơ...", description: "Nhãn khi đang tạo hồ sơ." },
  "create.success": { value: "Hồ sơ đã sẵn sàng!", description: "Thông báo tạo hồ sơ thành công." },
  "edit.nameLabel": { value: "Tên thân mật", description: "Nhãn chỉnh sửa tên hồ sơ." },
  "edit.namePlaceholder": { value: "Tên thân mật của bé", description: "Placeholder chỉnh sửa tên hồ sơ." },
  "edit.ageLabel": { value: "Nhóm tuổi", description: "Nhãn chỉnh sửa nhóm tuổi." },
  "edit.submit": { value: "Lưu thay đổi", description: "Nhãn lưu hồ sơ." },
  "edit.submitting": { value: "Đang lưu...", description: "Nhãn khi đang lưu hồ sơ." },
  "edit.success": { value: "Đã cập nhật hồ sơ", description: "Thông báo cập nhật hồ sơ thành công." },
  "list.ageGroup": { value: "Nhóm tuổi", description: "Nhãn nhóm tuổi trong danh sách hồ sơ." },
  "list.edit": { value: "Chỉnh sửa", description: "Nhãn chỉnh sửa hồ sơ." },
  "list.delete": { value: "Xóa", description: "Nhãn xóa hồ sơ." },
  "list.enterMap": { value: "Vào bản đồ", description: "Nhãn vào bản đồ nhiệm vụ." },
  "list.createMore": { value: "+ Tạo thêm hồ sơ bé", description: "Nhãn tạo thêm hồ sơ." },
  "list.deleteConfirm": {
    value: "Chuyển hồ sơ vào trạng thái chờ xóa?",
    description: "Xác nhận xóa mềm hồ sơ.",
  },
  "list.deleteSuccess": { value: "Đã ghi nhận yêu cầu xóa hồ sơ", description: "Thông báo xóa hồ sơ." },
  "list.selectError": { value: "Không thể chọn hồ sơ", description: "Lỗi chọn hồ sơ." },
  "list.deleteError": { value: "Không thể xóa hồ sơ", description: "Lỗi xóa hồ sơ." },
  "create.pageBadge": { value: "Hồ sơ riêng tư tối giản", description: "Nhãn đầu trang tạo Child Profile." },
  "create.pageTitle": { value: "Tạo hồ sơ cho bé", description: "Tiêu đề trang tạo Child Profile." },
  "create.pageDescription": {
    value: "Chỉ mất một chút để bé có hành trình phù hợp nhất.",
    description: "Mô tả trang tạo Child Profile.",
  },
  "list.imageAlt": { value: "Bống bên nhà cây", description: "Alt text ảnh trang chọn Child Profile." },
  "list.pageTitle": { value: "Chọn hồ sơ của bé", description: "Tiêu đề trang chọn Child Profile." },
  "list.pageDescription": {
    value: "Mỗi bé có hành trình và tiến độ riêng, được bảo vệ trong tài khoản phụ huynh.",
    description: "Mô tả trang chọn Child Profile.",
  },
  "list.emptyTitle": {
    value: "Gia đình chưa có hồ sơ bé",
    description: "Tiêu đề khi chưa có Child Profile.",
  },
  "list.emptyDescription": {
    value: "Tạo hồ sơ bằng tên thân mật và nhóm tuổi; không cần ngày sinh đầy đủ.",
    description: "Mô tả trạng thái chưa có Child Profile.",
  },
  "list.emptyAction": { value: "Tạo hồ sơ đầu tiên", description: "CTA tạo Child Profile đầu tiên." },
  "edit.pageTitle": { value: "Chỉnh sửa hồ sơ", description: "Tiêu đề trang chỉnh sửa Child Profile." },
  "edit.pageDescription": {
    value: "Chỉ lưu tên thân mật và nhóm tuổi phù hợp.",
    description: "Mô tả trang chỉnh sửa Child Profile.",
  },
});

export const parentContentEntries = defineContent("parent", {
  "shell.title": { value: "Khu vực phụ huynh", description: "Tiêu đề Parent Workspace." },
  "shell.viewing": { value: "Đang xem: {childName}", description: "Hồ sơ bé đang xem." },
  "shell.changeChild": { value: "Đổi bé", description: "Nhãn đổi Child Profile." },
  "nav.overview": { value: "Tổng quan", description: "Điều hướng tổng quan phụ huynh." },
  "nav.activity": { value: "Hoạt động", description: "Điều hướng hoạt động." },
  "nav.suggestions": { value: "Gợi ý", description: "Điều hướng gợi ý." },
  "nav.resources": { value: "Tài nguyên", description: "Điều hướng tài nguyên." },
  "nav.settings": { value: "Cài đặt", description: "Điều hướng cài đặt." },
  "nav.notifications": { value: "Thông báo", description: "Nhãn thông báo." },
  "nav.logout": { value: "Đăng xuất", description: "Nhãn đăng xuất." },
  "nav.openMenu": { value: "Mở menu phụ huynh", description: "Nhãn mở menu Parent Workspace." },
  "nav.closeMenu": { value: "Đóng menu phụ huynh", description: "Nhãn đóng menu Parent Workspace." },
  "dashboard.greeting": { value: "Xin chào, {parentName}", description: "Lời chào Parent Dashboard." },
  "dashboard.weekTitle": { value: "Tuần của {childName}", description: "Tiêu đề tuần của bé." },
  "dashboard.unread": { value: "{count} chưa đọc", description: "Số thông báo chưa đọc." },
  "dashboard.metricMissions": { value: "Nhiệm vụ", description: "Metric nhiệm vụ." },
  "dashboard.metricQuestions": { value: "Câu hoàn thành", description: "Metric câu hoàn thành." },
  "dashboard.metricMinutes": { value: "Phút khám phá", description: "Metric phút chơi." },
  "dashboard.metricBadges": { value: "Huy hiệu", description: "Metric huy hiệu." },
  "dashboard.recentTitle": { value: "Hoạt động gần đây", description: "Tiêu đề hoạt động gần đây." },
  "dashboard.viewAll": { value: "Xem tất cả", description: "Nhãn xem tất cả." },
  "dashboard.completed": { value: "Hoàn thành · {stars} sao", description: "Trạng thái hoàn thành session." },
  "dashboard.inProgress": { value: "Đang tiếp tục", description: "Trạng thái session đang chơi." },
  "dashboard.exited": { value: "Đã dừng", description: "Trạng thái session đã dừng." },
  "dashboard.emptyActivity": {
    value: "Bé chưa có hoạt động. Một nhiệm vụ ngắn là khởi đầu vừa đủ.",
    description: "Trạng thái hoạt động trống.",
  },
  "dashboard.suggestionLabel": { value: "Gợi ý trò chuyện", description: "Nhãn gợi ý trò chuyện." },
  "dashboard.suggestionDefaultTitle": {
    value: "Hỏi về cách bé nghĩ",
    description: "Tiêu đề gợi ý mặc định.",
  },
  "dashboard.suggestionDefaultQuestion": {
    value: "Con đã thử cách nào trước?",
    description: "Câu hỏi gợi ý mặc định.",
  },
  "dashboard.viewSuggestions": { value: "Xem thêm gợi ý", description: "Nhãn xem gợi ý." },
  "dashboard.skillsTitle": { value: "Thói quen tư duy nổi bật", description: "Tiêu đề kỹ năng nổi bật." },
  "dashboard.noSkills": { value: "Chưa có đủ dữ liệu", description: "Trạng thái kỹ năng trống." },
  "gate.title": { value: "Khu vực phụ huynh", description: "Tiêu đề Parent Gate." },
  "gate.description": {
    value: "Xác nhận người lớn trước khi hiển thị tiến độ và cài đặt gia đình.",
    description: "Mô tả Parent Gate.",
  },
  "gate.imageAlt": { value: "Lá chắn Parent Gate", description: "Alt text Parent Gate." },

  "gate.mathQuestion": { value: "17 + 6 = ?", description: "Phép tính mặc định của Parent Gate." },
  "gate.answerPlaceholder": { value: "Nhập kết quả", description: "Placeholder câu trả lời Parent Gate." },
  "gate.confirmTitle": { value: "Ba/mẹ xác nhận giúp Bống nhé", description: "Tiêu đề form Parent Gate." },
  "gate.pinPrompt": { value: "Nhập PIN phụ huynh", description: "Yêu cầu nhập PIN Parent Gate." },
  "gate.pinPlaceholder": { value: "Nhập PIN 4–8 chữ số", description: "Placeholder PIN Parent Gate." },
  "gate.submit": { value: "Mở khu vực phụ huynh", description: "Nhãn nút mở Parent Gate." },
  "gate.submitting": { value: "Đang kiểm tra...", description: "Nhãn khi kiểm tra Parent Gate." },
  "gate.error": { value: "Không thể mở khóa", description: "Lỗi Parent Gate mặc định." },
  "settings.audioTitle": { value: "Âm thanh và hiệu ứng", description: "Tiêu đề nhóm âm thanh." },
  "settings.soundEnabled": { value: "Âm thanh hướng dẫn", description: "Nhãn cài đặt âm thanh." },
  "settings.effectsEnabled": { value: "Hiệu ứng chúc mừng", description: "Nhãn cài đặt hiệu ứng." },
  "settings.notificationsTitle": { value: "Thông báo phụ huynh", description: "Tiêu đề nhóm thông báo." },
  "settings.missionCompleted": {
    value: "Khi bé hoàn thành nhiệm vụ",
    description: "Nhãn thông báo hoàn thành nhiệm vụ.",
  },
  "settings.suggestions": { value: "Khi có gợi ý trò chuyện mới", description: "Nhãn thông báo gợi ý." },
  "settings.weeklySummary": { value: "Tóm tắt tuần", description: "Nhãn thông báo tóm tắt tuần." },
  "settings.privacyTitle": { value: "Quyền riêng tư", description: "Tiêu đề nhóm quyền riêng tư." },
  "settings.analyticsTitle": {
    value: "Phân tích sản phẩm tối giản",
    description: "Nhãn phân tích tối giản.",
  },
  "settings.analyticsDescription": {
    value: "Không dùng quảng cáo, định vị hoặc hồ sơ định danh của bé.",
    description: "Mô tả phân tích tối giản.",
  },
  "settings.pinTitle": { value: "PIN phụ huynh", description: "Tiêu đề nhóm PIN." },
  "settings.pinDescription": {
    value: "Đặt 4–8 chữ số để thay phép tính ở Parent Gate.",
    description: "Mô tả cài đặt PIN.",
  },
  "settings.pinPlaceholder": { value: "PIN mới", description: "Placeholder PIN mới." },
  "settings.save": { value: "Lưu cài đặt", description: "Nhãn lưu cài đặt." },
  "settings.saving": { value: "Đang lưu...", description: "Nhãn khi đang lưu cài đặt." },
  "settings.saved": { value: "Đã lưu cài đặt", description: "Thông báo lưu cài đặt thành công." },
  "settings.dataTitle": { value: "Dữ liệu gia đình", description: "Tiêu đề nhóm dữ liệu gia đình." },
  "settings.export": { value: "Yêu cầu xuất dữ liệu", description: "Nhãn xuất dữ liệu." },
  "settings.exportReady": { value: "Gói dữ liệu đã sẵn sàng", description: "Thông báo gói xuất sẵn sàng." },
  "settings.resetProgress": { value: "Đặt lại tiến độ bé", description: "Nhãn đặt lại tiến độ." },
  "settings.resetConfirm": {
    value: "Xóa toàn bộ tiến độ của hồ sơ đang chọn?",
    description: "Xác nhận đặt lại tiến độ.",
  },
  "settings.resetSuccess": { value: "Đã xóa tiến độ", description: "Thông báo đặt lại tiến độ thành công." },
  "settings.deleteRequest": { value: "Yêu cầu xóa dữ liệu", description: "Nhãn yêu cầu xóa dữ liệu." },
  "settings.deleteConfirm": {
    value: "Gửi yêu cầu xóa dữ liệu gia đình?",
    description: "Xác nhận yêu cầu xóa dữ liệu.",
  },
  "settings.deleteSuccess": {
    value: "Đã ghi nhận yêu cầu xóa",
    description: "Thông báo yêu cầu xóa được ghi nhận.",
  },
  "activity.title": { value: "Lịch sử hoạt động", description: "Tiêu đề lịch sử hoạt động của bé." },
  "activity.description": {
    value: "Theo dõi hành trình của riêng bé, không so sánh với trẻ khác.",
    description: "Mô tả lịch sử hoạt động.",
  },
  "activity.allStatuses": { value: "Tất cả trạng thái", description: "Lựa chọn mọi trạng thái session." },
  "activity.completed": { value: "Đã hoàn thành", description: "Trạng thái session hoàn thành." },
  "activity.inProgress": { value: "Đang tiếp tục", description: "Trạng thái session đang tiếp tục." },
  "activity.exited": { value: "Đã dừng", description: "Trạng thái session đã dừng." },
  "activity.filter": { value: "Lọc hoạt động", description: "Nhãn nút lọc hoạt động." },
  "activity.questions": {
    value: "{correct}/{total} câu",
    description: "Số câu đúng trên tổng số câu.",
  },
  "activity.hints": { value: "{count} gợi ý", description: "Số gợi ý đã dùng." },
  "activity.retries": { value: "{count} lần thử lại", description: "Số lần thử lại." },
  "activity.empty": {
    value: "Không có hoạt động phù hợp bộ lọc.",
    description: "Trạng thái lịch sử hoạt động trống.",
  },
});
