import { defineContent } from "@/content/define";

export const missionEditorContentEntries = defineContent("admin", {
  "missionEditor.modeCreate": { value: "Tạo mới", description: "Chế độ tạo Mission." },
  "missionEditor.modeEdit": { value: "Chỉnh sửa", description: "Chế độ sửa Mission." },
  "missionEditor.newTitle": { value: "Nhiệm vụ mới", description: "Tiêu đề Mission mới." },
  "missionEditor.basicTitle": { value: "1. Thông tin cơ bản", description: "Tiêu đề phần cơ bản." },
  "missionEditor.questionsTitle": { value: "2. Câu hỏi", description: "Tiêu đề phần câu hỏi." },
  "missionEditor.safetyTitle": { value: "3. Safety Checklist", description: "Tiêu đề checklist." },
  "missionEditor.previewRules": { value: "Quy tắc xuất bản", description: "Tiêu đề quy tắc publish." },
  "missionEditor.saveDraft": { value: "Lưu bản nháp", description: "Nhãn lưu Mission draft." },
  "missionEditor.saving": { value: "Đang lưu...", description: "Nhãn khi lưu Mission." },
  "missionEditor.submit": { value: "Lưu và gửi duyệt", description: "Nhãn gửi Mission review." },
  "missionEditor.submitting": { value: "Đang gửi...", description: "Nhãn khi gửi review." },
  "missionEditor.saved": { value: "Đã lưu bản nháp vào PostgreSQL", description: "Thông báo lưu draft." },
  "missionEditor.submitted": {
    value: "Đã tạo phiên bản bất biến và gửi reviewer",
    description: "Thông báo gửi review.",
  },
  "missionEditor.addQuestion": { value: "Thêm câu hỏi", description: "Nhãn thêm câu hỏi." },
  "missionEditor.question": { value: "Câu", description: "Nhãn thứ tự câu hỏi." },
  "missionEditor.questionType": { value: "Loại câu hỏi", description: "Nhãn loại câu hỏi." },
  "missionEditor.difficulty": { value: "Độ khó", description: "Nhãn độ khó." },
  "missionEditor.prompt": { value: "Câu hỏi", description: "Nhãn prompt câu hỏi." },
  "missionEditor.instruction": { value: "Hướng dẫn", description: "Nhãn hướng dẫn câu hỏi." },
  "missionEditor.payload": { value: "Payload JSON", description: "Nhãn payload câu hỏi." },
  "missionEditor.answer": { value: "Đáp án đúng JSON", description: "Nhãn đáp án câu hỏi." },
  "missionEditor.hints": { value: "Gợi ý, mỗi dòng là một cấp", description: "Nhãn gợi ý." },
  "missionEditor.correctFeedback": { value: "Phản hồi đúng", description: "Nhãn phản hồi đúng." },
  "missionEditor.incorrectFeedback": { value: "Phản hồi chưa đúng", description: "Nhãn phản hồi chưa đúng." },
  "missionEditor.type.singleChoice": {
    value: "Chọn một đáp án",
    description: "Tên loại câu hỏi single choice.",
  },
  "missionEditor.type.pattern": { value: "Chuỗi quy luật", description: "Tên loại câu hỏi pattern." },
  "missionEditor.type.dragDrop": { value: "Kéo/thả vào vị trí", description: "Tên loại câu hỏi drag drop." },
  "missionEditor.type.fillAnswer": { value: "Điền đáp án", description: "Tên loại câu hỏi fill answer." },
  "missionEditor.type.sorting": { value: "Sắp xếp thứ tự", description: "Tên loại câu hỏi sorting." },
  "missionEditor.safety.ageAppropriate": { value: "Độ tuổi phù hợp", description: "Tiêu chí độ tuổi." },
  "missionEditor.safety.hintsSupportive": { value: "Gợi ý mang tính hỗ trợ", description: "Tiêu chí gợi ý." },
  "missionEditor.safety.feedbackPositive": { value: "Phản hồi tích cực", description: "Tiêu chí phản hồi." },
  "missionEditor.safety.noProhibitedClaims": {
    value: "Không có tuyên bố bị cấm",
    description: "Tiêu chí tuyên bố.",
  },
  "missionEditor.safety.noExternalLinks": {
    value: "Không có liên kết ngoài",
    description: "Tiêu chí liên kết.",
  },
  "missionEditor.safety.languageAndImagesSafe": {
    value: "Ngôn ngữ và hình ảnh an toàn",
    description: "Tiêu chí nội dung an toàn.",
  },
  "missionEditor.title": { value: "Tiêu đề", description: "Nhãn tiêu đề Mission." },
  "missionEditor.slug": { value: "Slug", description: "Nhãn slug Mission." },
  "missionEditor.subtitle": { value: "Phụ đề", description: "Nhãn phụ đề Mission." },
  "missionEditor.shortDescription": { value: "Mô tả ngắn", description: "Nhãn mô tả ngắn Mission." },
  "missionEditor.storyIntro": { value: "Câu chuyện dẫn dắt", description: "Nhãn story intro." },
  "missionEditor.world": { value: "Thế giới", description: "Nhãn Mission World." },
  "missionEditor.primarySkill": { value: "Kỹ năng chính", description: "Nhãn kỹ năng chính." },
  "missionEditor.secondarySkills": { value: "Kỹ năng phụ", description: "Nhãn kỹ năng phụ." },
  "missionEditor.reward": { value: "Phần thưởng", description: "Nhãn phần thưởng." },
  "missionEditor.noReward": { value: "Không có huy hiệu", description: "Tùy chọn không huy hiệu." },
  "missionEditor.minutes": { value: "Thời gian (phút)", description: "Nhãn thời lượng Mission." },
  "missionEditor.cover": { value: "Ảnh bìa URL", description: "Nhãn cover Mission." },
  "missionEditor.ageGroups": { value: "Nhóm tuổi", description: "Nhãn nhóm tuổi Mission." },
  "missionEditor.allowReplay": { value: "Cho phép chơi lại", description: "Nhãn chơi lại." },
  "missionEditor.randomize": { value: "Đảo đáp án khi chơi", description: "Nhãn đảo đáp án." },
  "missionEditor.safetyComplete": { value: "Đạt 100%", description: "Checklist hoàn tất." },
  "missionEditor.safetyIncomplete": { value: "Chưa hoàn tất", description: "Checklist chưa hoàn tất." },
  "missionEditor.previewAlt": { value: "Preview ảnh bìa", description: "Alt preview cover." },
  "missionEditor.ruleDraft": {
    value: "Draft không ghi đè phiên bản đang publish.",
    description: "Quy tắc draft.",
  },
  "missionEditor.ruleSnapshot": { value: "Submit tạo snapshot bất biến.", description: "Quy tắc snapshot." },
  "missionEditor.ruleReview": {
    value: "Reviewer duyệt hoặc trả lại với nhận xét.",
    description: "Quy tắc review.",
  },
  "missionEditor.rulePublish": {
    value: "Chỉ phiên bản approved mới được publish.",
    description: "Quy tắc publish.",
  },
});
