import { defineContent } from "@/content/define";

export const missionEditorContentEntries = defineContent("admin", {
  "missionEditor.modeCreate": { value: "Tạo nhiệm vụ mới", description: "Chế độ tạo nhiệm vụ." },
  "missionEditor.modeEdit": { value: "Đang chỉnh sửa nhiệm vụ", description: "Chế độ sửa nhiệm vụ." },
  "missionEditor.newTitle": { value: "Nhiệm vụ chưa đặt tên", description: "Tiêu đề nhiệm vụ mới." },
  "missionEditor.basicTitle": { value: "1. Nội dung hiển thị", description: "Tiêu đề phần nội dung." },
  "missionEditor.questionsTitle": {
    value: "2. Câu hỏi trong nhiệm vụ",
    description: "Tiêu đề phần câu hỏi.",
  },
  "missionEditor.safetyTitle": {
    value: "3. Kiểm tra an toàn trước khi gửi duyệt",
    description: "Tiêu đề kiểm tra an toàn.",
  },
  "missionEditor.previewRules": { value: "Điều gì xảy ra sau khi soạn?", description: "Tiêu đề quy trình." },
  "missionEditor.saveDraft": { value: "Lưu để tiếp tục sau", description: "Nhãn lưu bản nháp." },
  "missionEditor.saving": { value: "Đang lưu...", description: "Nhãn khi lưu Mission." },
  "missionEditor.submit": { value: "Gửi người kiểm duyệt", description: "Nhãn gửi kiểm duyệt." },
  "missionEditor.submitting": { value: "Đang gửi...", description: "Nhãn khi gửi kiểm duyệt." },
  "missionEditor.saved": { value: "Đã lưu bản nháp", description: "Thông báo lưu bản nháp." },
  "missionEditor.submitted": {
    value: "Đã gửi nhiệm vụ đến người kiểm duyệt",
    description: "Thông báo gửi kiểm duyệt.",
  },
  "missionEditor.addQuestion": { value: "Thêm câu hỏi", description: "Nhãn thêm câu hỏi." },
  "missionEditor.question": { value: "Câu", description: "Nhãn thứ tự câu hỏi." },
  "missionEditor.questionType": { value: "Loại câu hỏi", description: "Nhãn loại câu hỏi." },
  "missionEditor.difficulty": { value: "Độ khó", description: "Nhãn độ khó." },
  "missionEditor.prompt": { value: "Câu hỏi", description: "Nhãn prompt câu hỏi." },
  "missionEditor.instruction": { value: "Hướng dẫn", description: "Nhãn hướng dẫn câu hỏi." },
  "missionEditor.hints": { value: "Gợi ý, mỗi dòng là một cấp", description: "Nhãn gợi ý." },
  "missionEditor.correctFeedback": { value: "Phản hồi đúng", description: "Nhãn phản hồi đúng." },
  "missionEditor.incorrectFeedback": { value: "Phản hồi chưa đúng", description: "Nhãn phản hồi chưa đúng." },
  "missionEditor.type.singleChoice": {
    value: "Chọn một đáp án",
    description: "Tên loại câu hỏi single choice.",
  },
  "missionEditor.type.pattern": { value: "Chuỗi quy luật", description: "Tên loại câu hỏi pattern." },
  "missionEditor.type.dragDrop": { value: "Kéo/thả vào vị trí", description: "Tên loại câu hỏi drag drop." },
  "missionEditor.type.fillAnswer": { value: "Điền đáp án", description: "Tên loại câu hỏi fill answer." },
  "missionEditor.type.sorting": { value: "Sắp xếp thứ tự", description: "Tên loại câu hỏi sorting." },
  "missionEditor.safety.ageAppropriate": {
    value: "Nội dung phù hợp nhóm tuổi đã chọn",
    description: "Tiêu chí độ tuổi.",
  },
  "missionEditor.safety.hintsSupportive": {
    value: "Gợi ý giúp bé tiếp tục suy nghĩ",
    description: "Tiêu chí gợi ý.",
  },
  "missionEditor.safety.feedbackPositive": {
    value: "Phản hồi tích cực, không gây áp lực",
    description: "Tiêu chí phản hồi.",
  },
  "missionEditor.safety.noProhibitedClaims": {
    value: "Không có nội dung khẳng định quá mức hoặc gây hiểu lầm",
    description: "Tiêu chí tuyên bố.",
  },
  "missionEditor.safety.noExternalLinks": {
    value: "Không dẫn trẻ ra website bên ngoài",
    description: "Tiêu chí liên kết.",
  },
  "missionEditor.safety.languageAndImagesSafe": {
    value: "Ngôn ngữ và hình ảnh an toàn cho trẻ",
    description: "Tiêu chí nội dung an toàn.",
  },
  "missionEditor.title": { value: "Tên nhiệm vụ", description: "Nhãn tên nhiệm vụ." },
  "missionEditor.slug": { value: "Mã đường dẫn", description: "Nhãn mã đường dẫn." },
  "missionEditor.subtitle": { value: "Câu giới thiệu ngắn", description: "Nhãn câu giới thiệu." },
  "missionEditor.shortDescription": { value: "Mô tả trên thẻ nhiệm vụ", description: "Nhãn mô tả nhiệm vụ." },
  "missionEditor.storyIntro": { value: "Câu chuyện mở đầu", description: "Nhãn câu chuyện mở đầu." },
  "missionEditor.world": { value: "Chủ đề nhiệm vụ", description: "Nhãn chọn chủ đề nhiệm vụ." },
  "missionEditor.primarySkill": { value: "Kỹ năng chính", description: "Nhãn kỹ năng chính." },
  "missionEditor.secondarySkills": { value: "Kỹ năng phụ", description: "Nhãn kỹ năng phụ." },
  "missionEditor.reward": { value: "Phần thưởng", description: "Nhãn phần thưởng." },
  "missionEditor.noReward": { value: "Không có huy hiệu", description: "Tùy chọn không huy hiệu." },
  "missionEditor.minutes": { value: "Thời gian (phút)", description: "Nhãn thời lượng Mission." },
  "missionEditor.cover": { value: "Ảnh bìa nhiệm vụ", description: "Nhãn tải ảnh bìa nhiệm vụ." },
  "missionEditor.ageGroups": { value: "Nhóm tuổi", description: "Nhãn nhóm tuổi Mission." },
  "missionEditor.allowReplay": { value: "Cho phép chơi lại", description: "Nhãn chơi lại." },
  "missionEditor.randomize": { value: "Đổi thứ tự đáp án khi chơi", description: "Nhãn đổi thứ tự đáp án." },
  "missionEditor.previewAlt": {
    value: "Ảnh bìa nhiệm vụ",
    description: "Mô tả ảnh bìa trong phần xem trước.",
  },
});
