import { defineContent } from "@/content/define";

export const commonContentEntries = defineContent("common", {
  "brand.name": { value: "Suy Luận Nhí", description: "Tên thương hiệu hiển thị toàn hệ thống." },
  "brand.description": {
    value: "Nhiệm vụ vui giúp bé luyện cách nghĩ an toàn và tích cực.",
    description: "Mô tả mặc định cho metadata và landing page.",
  },
  "actions.save": { value: "Lưu thay đổi", description: "Nhãn nút lưu chung." },
  "actions.retry": { value: "Thử lại", description: "Nhãn thử lại thao tác." },
  "states.loading": { value: "Đang tải dữ liệu...", description: "Trạng thái tải dữ liệu chung." },
  "states.empty": { value: "Chưa có dữ liệu", description: "Trạng thái dữ liệu trống chung." },
  "errors.generic": { value: "Có lỗi xảy ra. Vui lòng thử lại.", description: "Thông báo lỗi chung." },
  "errors.network": { value: "Không thể kết nối máy chủ", description: "Thông báo lỗi mạng chung." },
});

export const gameplayContentEntries = defineContent("gameplay", {
  "actions.checkAnswer": { value: "Kiểm tra đáp án", description: "Nhãn nút kiểm tra đáp án." },
  "actions.hint": { value: "Cho con một gợi ý", description: "Nhãn nút lấy gợi ý." },
  "feedback.correctTitle": { value: "Tuyệt vời!", description: "Tiêu đề phản hồi đúng." },
  "feedback.retryTitle": { value: "Chưa trúng thôi!", description: "Tiêu đề phản hồi thử lại." },
  "mission.start": { value: "Bắt đầu nhiệm vụ", description: "Nhãn bắt đầu nhiệm vụ." },
  "mission.starting": { value: "Bống đang chuẩn bị...", description: "Nhãn khi bắt đầu nhiệm vụ." },
  "mission.startError": { value: "Không thể bắt đầu nhiệm vụ", description: "Lỗi bắt đầu nhiệm vụ." },
  "actions.checking": { value: "Đang kiểm tra...", description: "Nhãn khi kiểm tra đáp án." },
  "actions.loadingHint": { value: "Đang lấy gợi ý...", description: "Nhãn khi tải gợi ý." },
  "actions.nextQuestion": { value: "Câu tiếp theo →", description: "Nhãn sang câu tiếp theo." },
  "actions.claimBadge": { value: "Nhận huy hiệu", description: "Nhãn nhận huy hiệu." },
  "actions.retry": { value: "Thử lại", description: "Nhãn thử lại câu hỏi." },
  "actions.exit": { value: "Dừng và lưu tiến độ", description: "Nhãn dừng Mission Session." },
  "actions.exiting": { value: "Đang lưu tiến độ...", description: "Nhãn khi dừng Mission Session." },
  "errors.answer": { value: "Không thể ghi nhận đáp án", description: "Lỗi gửi đáp án." },
  "errors.hint": { value: "Không thể lấy gợi ý", description: "Lỗi lấy gợi ý." },
  "errors.complete": { value: "Không thể hoàn thành nhiệm vụ", description: "Lỗi hoàn thành nhiệm vụ." },
  "errors.exit": { value: "Không thể lưu tiến độ", description: "Lỗi dừng Mission Session." },
  "hint.imageAlt": { value: "Bống đang gợi ý", description: "Alt text linh vật gợi ý." },
});

export const adminContentEntries = defineContent("admin", {
  "content.title": { value: "Quản lý nội dung hệ thống", description: "Tiêu đề trang Content Management." },
  "content.description": {
    value: "Chỉnh sửa UI copy, thông báo và nội dung dùng chung mà không cần sửa component.",
    description: "Mô tả trang Content Management.",
  },
  "content.searchPlaceholder": {
    value: "Tìm namespace, key hoặc mô tả nội dung",
    description: "Placeholder tìm nội dung quản trị.",
  },
  "content.valuePlaceholder": {
    value: "Nhập chuỗi hoặc JSON hợp lệ",
    description: "Placeholder trình chỉnh sửa content value.",
  },
  "content.active": { value: "Đang sử dụng", description: "Nhãn trạng thái content đang dùng." },
  "content.save": { value: "Lưu nội dung", description: "Nhãn nút lưu content." },
  "content.saving": { value: "Đang lưu...", description: "Nhãn khi đang lưu content." },
  "content.empty": {
    value: "Không tìm thấy nội dung phù hợp.",
    description: "Trạng thái tìm content trống.",
  },
  "media.uploadTitle": { value: "Tải media mới", description: "Tiêu đề form tải media." },
  "media.uploadDescription": {
    value: "Ảnh tối đa 10MB, audio tối đa 20MB. Alt text là bắt buộc.",
    description: "Hướng dẫn tải media.",
  },
  "media.altLabel": { value: "Mô tả hình ảnh hoặc audio", description: "Nhãn alt text media." },
  "media.altPlaceholder": { value: "Mô tả hình ảnh hoặc audio", description: "Placeholder alt text media." },
  "media.upload": { value: "Tải lên", description: "Nhãn nút tải media." },
  "media.uploading": { value: "Đang tải...", description: "Nhãn khi tải media." },
  "media.uploadSuccess": {
    value: "Đã tải media lên storage",
    description: "Thông báo tải media thành công.",
  },
  "media.reviewOnly": {
    value: "Reviewer có thể duyệt hoặc từ chối media; chỉ content admin và super admin được tải tệp mới.",
    description: "Thông báo quyền media.",
  },
  "media.approve": { value: "Duyệt media", description: "Nhãn duyệt media." },
  "media.reject": { value: "Từ chối media", description: "Nhãn từ chối media." },
  "media.delete": { value: "Xóa media", description: "Nhãn xóa media." },
  "media.deleteConfirm": { value: "Xóa media này khỏi storage?", description: "Xác nhận xóa media." },
  "settings.title": { value: "System settings", description: "Tiêu đề quản lý system settings." },
  "settings.jsonLabel": { value: "Giá trị JSON", description: "Nhãn giá trị system setting." },
  "settings.jsonPlaceholder": { value: "Nhập JSON hợp lệ", description: "Placeholder system setting." },
  "settings.save": { value: "Lưu", description: "Nhãn lưu system setting." },
  "settings.saving": { value: "Đang lưu...", description: "Nhãn khi lưu system setting." },
  "settings.saved": { value: "Đã lưu system setting", description: "Thông báo lưu system setting." },
  "settings.createTitle": { value: "Thêm setting", description: "Tiêu đề tạo system setting." },
  "settings.keyLabel": { value: "Setting key", description: "Nhãn key system setting." },
  "settings.keyPlaceholder": { value: "key.ví_dụ", description: "Placeholder key system setting." },
  "settings.create": { value: "Thêm setting", description: "Nhãn tạo system setting." },
  "world.createTitle": { value: "Tạo Mission World mới", description: "Tiêu đề tạo Mission World." },
  "world.slugLabel": { value: "Slug", description: "Nhãn slug Mission World." },
  "world.titleLabel": { value: "Tiêu đề", description: "Nhãn tiêu đề Mission World." },
  "world.subtitleLabel": { value: "Phụ đề", description: "Nhãn phụ đề Mission World." },
  "world.descriptionLabel": { value: "Mô tả", description: "Nhãn mô tả Mission World." },
  "world.coverLabel": { value: "Cover URL", description: "Nhãn cover Mission World." },
  "world.sortOrderLabel": { value: "Thứ tự", description: "Nhãn thứ tự Mission World." },
  "world.themeLabel": { value: "Màu chủ đề", description: "Nhãn màu Mission World." },
  "world.statusLabel": { value: "Trạng thái", description: "Nhãn trạng thái Mission World." },
  "world.create": { value: "Tạo thế giới", description: "Nhãn tạo Mission World." },
  "world.creating": { value: "Đang tạo...", description: "Nhãn khi tạo Mission World." },
  "world.update": { value: "Lưu", description: "Nhãn cập nhật Mission World." },
  "world.updating": { value: "Đang lưu...", description: "Nhãn khi cập nhật Mission World." },
  "world.createSuccess": { value: "Đã tạo Mission World", description: "Thông báo tạo Mission World." },
  "world.updateSuccess": {
    value: "Đã cập nhật Mission World",
    description: "Thông báo cập nhật Mission World.",
  },
});
