import { defineContent } from "@/content/define";

export const commonContentEntries = defineContent("common", {
  "brand.name": { value: "Suy Luận Nhí", description: "Tên thương hiệu hiển thị toàn hệ thống." },
  "brand.description": {
    value: "Nhiệm vụ vui giúp bé luyện cách nghĩ an toàn và tích cực.",
    description: "Mô tả mặc định cho metadata và landing page.",
  },
  "actions.save": { value: "Lưu thay đổi", description: "Nhãn nút lưu chung." },
  "actions.retry": { value: "Thử lại", description: "Nhãn thử lại thao tác." },
  "states.loading": { value: "Đang tải dữ liệu...", description: "Trạng thái tải dữ liệu chung." },
  "states.empty": { value: "Chưa có dữ liệu", description: "Trạng thái dữ liệu trống chung." },
  "errors.generic": { value: "Có lỗi xảy ra. Vui lòng thử lại.", description: "Thông báo lỗi chung." },
  "errors.network": { value: "Không thể kết nối máy chủ", description: "Thông báo lỗi mạng chung." },
});

export const gameplayContentEntries = defineContent("gameplay", {
  "actions.checkAnswer": { value: "Kiểm tra đáp án", description: "Nhãn nút kiểm tra đáp án." },
  "actions.hint": { value: "Cho con một gợi ý", description: "Nhãn nút lấy gợi ý." },
  "feedback.correctTitle": { value: "Tuyệt vời!", description: "Tiêu đề phản hồi đúng." },
  "feedback.retryTitle": { value: "Chưa trúng thôi!", description: "Tiêu đề phản hồi thử lại." },
  "mission.start": { value: "Bắt đầu nhiệm vụ", description: "Nhãn bắt đầu nhiệm vụ." },
  "mission.starting": { value: "Bống đang chuẩn bị...", description: "Nhãn khi bắt đầu nhiệm vụ." },
  "mission.startError": { value: "Không thể bắt đầu nhiệm vụ", description: "Lỗi bắt đầu nhiệm vụ." },
  "actions.checking": { value: "Đang kiểm tra...", description: "Nhãn khi kiểm tra đáp án." },
  "actions.loadingHint": { value: "Đang lấy gợi ý...", description: "Nhãn khi tải gợi ý." },
  "actions.nextQuestion": { value: "Câu tiếp theo →", description: "Nhãn sang câu tiếp theo." },
  "actions.claimBadge": { value: "Nhận huy hiệu", description: "Nhãn nhận huy hiệu." },
  "actions.retry": { value: "Thử lại", description: "Nhãn thử lại câu hỏi." },
  "actions.exit": { value: "Dừng và lưu tiến độ", description: "Nhãn dừng Mission Session." },
  "actions.exiting": { value: "Đang lưu tiến độ...", description: "Nhãn khi dừng Mission Session." },
  "errors.answer": { value: "Không thể ghi nhận đáp án", description: "Lỗi gửi đáp án." },
  "errors.hint": { value: "Không thể lấy gợi ý", description: "Lỗi lấy gợi ý." },
  "errors.complete": { value: "Không thể hoàn thành nhiệm vụ", description: "Lỗi hoàn thành nhiệm vụ." },
  "errors.exit": { value: "Không thể lưu tiến độ", description: "Lỗi dừng Mission Session." },
  "hint.imageAlt": { value: "Bống đang gợi ý", description: "Alt text linh vật gợi ý." },
});

export const adminContentEntries = defineContent("admin", {
  "content.title": { value: "Quản lý nội dung hệ thống", description: "Tiêu đề trang Content Management." },
  "content.description": {
    value: "Chỉnh sửa UI copy, thông báo và nội dung dùng chung mà không cần sửa component.",
    description: "Mô tả trang Content Management.",
  },
  "content.searchPlaceholder": {
    value: "Tìm theo trang, mô tả hoặc câu chữ đang hiển thị",
    description: "Placeholder tìm nội dung giao diện.",
  },
  "content.valuePlaceholder": {
    value: "Nhập nội dung hiển thị",
    description: "Placeholder trình chỉnh sửa nội dung.",
  },
  "content.active": { value: "Đang sử dụng", description: "Nhãn trạng thái content đang dùng." },
  "content.save": { value: "Lưu nội dung", description: "Nhãn nút lưu content." },
  "content.saving": { value: "Đang lưu...", description: "Nhãn khi đang lưu content." },
  "content.empty": {
    value: "Không tìm thấy nội dung phù hợp.",
    description: "Trạng thái tìm content trống.",
  },
  "media.uploadTitle": { value: "Tải tư liệu mới", description: "Tiêu đề form tải tư liệu." },
  "media.uploadDescription": {
    value: "Ảnh tối đa 10MB, âm thanh tối đa 20MB. Hãy mô tả rõ nội dung để hỗ trợ khả năng tiếp cận.",
    description: "Hướng dẫn tải tư liệu.",
  },
  "media.altLabel": { value: "Mô tả nội dung tư liệu", description: "Nhãn mô tả tư liệu." },
  "media.altPlaceholder": {
    value: "Mô tả hình ảnh hoặc âm thanh",
    description: "Placeholder mô tả tư liệu.",
  },
  "media.upload": { value: "Tải lên", description: "Nhãn nút tải media." },
  "media.uploading": { value: "Đang tải...", description: "Nhãn khi tải media." },
  "media.uploadSuccess": {
    value: "Đã tải tư liệu lên thư viện",
    description: "Thông báo tải tư liệu thành công.",
  },
  "media.reviewOnly": {
    value: "Bạn có thể kiểm tra và duyệt tư liệu. Chỉ biên tập viên hoặc quản trị viên mới được tải tệp mới.",
    description: "Thông báo quyền tư liệu.",
  },
  "media.approve": { value: "Duyệt tư liệu", description: "Nhãn duyệt tư liệu." },
  "media.reject": { value: "Đánh dấu tư liệu không phù hợp", description: "Nhãn từ chối tư liệu." },
  "media.delete": { value: "Xóa tư liệu", description: "Nhãn xóa tư liệu." },
  "media.deleteConfirm": { value: "Xóa vĩnh viễn tư liệu này?", description: "Xác nhận xóa tư liệu." },
  "settings.title": { value: "Cài đặt nâng cao", description: "Tiêu đề quản lý cài đặt." },
  "settings.jsonLabel": { value: "Giá trị cấu hình", description: "Nhãn giá trị cấu hình." },
  "settings.jsonPlaceholder": { value: "Nhập giá trị cấu hình hợp lệ", description: "Placeholder cấu hình." },
  "settings.save": { value: "Lưu", description: "Nhãn lưu cấu hình." },
  "settings.saving": { value: "Đang lưu...", description: "Nhãn khi lưu cấu hình." },
  "settings.saved": { value: "Đã lưu cấu hình", description: "Thông báo lưu cấu hình." },
  "settings.createTitle": { value: "Thêm cấu hình", description: "Tiêu đề tạo cấu hình." },
  "settings.keyLabel": { value: "Mã cấu hình", description: "Nhãn mã cấu hình." },
  "settings.keyPlaceholder": { value: "Ví dụ: feature.enabled", description: "Placeholder mã cấu hình." },
  "settings.create": { value: "Thêm cấu hình", description: "Nhãn tạo cấu hình." },
  "world.createTitle": { value: "Tạo thế giới nhiệm vụ mới", description: "Tiêu đề tạo thế giới nhiệm vụ." },
  "world.slugLabel": { value: "Mã đường dẫn", description: "Nhãn mã đường dẫn thế giới." },
  "world.titleLabel": { value: "Tên thế giới", description: "Nhãn tên thế giới." },
  "world.subtitleLabel": { value: "Câu giới thiệu ngắn", description: "Nhãn câu giới thiệu thế giới." },
  "world.descriptionLabel": { value: "Mô tả cho phụ huynh và trẻ", description: "Nhãn mô tả thế giới." },
  "world.coverLabel": { value: "Đường dẫn ảnh bìa", description: "Nhãn ảnh bìa thế giới." },
  "world.sortOrderLabel": { value: "Vị trí trên bản đồ", description: "Nhãn thứ tự thế giới." },
  "world.themeLabel": { value: "Màu chủ đề", description: "Nhãn màu thế giới." },
  "world.statusLabel": { value: "Trạng thái hiển thị", description: "Nhãn trạng thái thế giới." },
  "world.create": { value: "Tạo thế giới", description: "Nhãn tạo thế giới." },
  "world.creating": { value: "Đang tạo...", description: "Nhãn khi tạo thế giới." },
  "world.update": { value: "Lưu thay đổi", description: "Nhãn cập nhật thế giới." },
  "world.updating": { value: "Đang lưu...", description: "Nhãn khi cập nhật thế giới." },
  "world.createSuccess": { value: "Đã tạo thế giới nhiệm vụ", description: "Thông báo tạo thế giới." },
  "world.updateSuccess": {
    value: "Đã cập nhật thế giới nhiệm vụ",
    description: "Thông báo cập nhật thế giới.",
  },
});
