import { defineContent } from "@/content/define";

export const commonContentEntries = defineContent("common", {
  "brand.name": { value: "Suy Luận Nhí", description: "Tên thương hiệu hiển thị toàn hệ thống." },
  "brand.description": {
    value: "Nhiệm vụ vui giúp bé luyện cách nghĩ an toàn và tích cực.",
    description: "Mô tả mặc định cho metadata và landing page.",
  },
  "actions.save": { value: "Lưu thay đổi", description: "Nhãn nút lưu chung." },
  "actions.retry": { value: "Thử lại", description: "Nhãn thử lại thao tác." },
  "states.loading": { value: "Đang tải dữ liệu...", description: "Trạng thái tải dữ liệu chung." },
  "states.empty": { value: "Chưa có dữ liệu", description: "Trạng thái dữ liệu trống chung." },
  "errors.generic": { value: "Có lỗi xảy ra. Vui lòng thử lại.", description: "Thông báo lỗi chung." },
  "errors.network": { value: "Không thể kết nối máy chủ", description: "Thông báo lỗi mạng chung." },
});

export const gameplayContentEntries = defineContent("gameplay", {
  "actions.checkAnswer": { value: "Kiểm tra đáp án", description: "Nhãn nút kiểm tra đáp án." },
  "actions.hint": { value: "Cho con một gợi ý", description: "Nhãn nút lấy gợi ý." },
  "feedback.correctTitle": { value: "Tuyệt vời!", description: "Tiêu đề phản hồi đúng." },
  "feedback.retryTitle": { value: "Chưa trúng thôi!", description: "Tiêu đề phản hồi thử lại." },
  "mission.start": { value: "Bắt đầu nhiệm vụ", description: "Nhãn bắt đầu nhiệm vụ." },
  "mission.starting": { value: "Bống đang chuẩn bị...", description: "Nhãn khi bắt đầu nhiệm vụ." },
  "mission.startError": { value: "Không thể bắt đầu nhiệm vụ", description: "Lỗi bắt đầu nhiệm vụ." },
  "actions.checking": { value: "Đang kiểm tra...", description: "Nhãn khi kiểm tra đáp án." },
  "actions.loadingHint": { value: "Đang lấy gợi ý...", description: "Nhãn khi tải gợi ý." },
  "actions.nextQuestion": { value: "Câu tiếp theo →", description: "Nhãn sang câu tiếp theo." },
  "actions.claimBadge": { value: "Nhận huy hiệu", description: "Nhãn nhận huy hiệu." },
  "actions.retry": { value: "Thử lại", description: "Nhãn thử lại câu hỏi." },
  "actions.exit": { value: "Dừng và lưu tiến độ", description: "Nhãn dừng Mission Session." },
  "actions.exiting": { value: "Đang lưu tiến độ...", description: "Nhãn khi dừng Mission Session." },
  "errors.answer": { value: "Không thể ghi nhận đáp án", description: "Lỗi gửi đáp án." },
  "errors.hint": { value: "Không thể lấy gợi ý", description: "Lỗi lấy gợi ý." },
  "errors.complete": { value: "Không thể hoàn thành nhiệm vụ", description: "Lỗi hoàn thành nhiệm vụ." },
  "errors.exit": { value: "Không thể lưu tiến độ", description: "Lỗi dừng Mission Session." },
  "hint.imageAlt": { value: "Bống đang gợi ý", description: "Alt text linh vật gợi ý." },
});

export const adminContentEntries = defineContent("admin", {
  "content.title": { value: "Chỉnh sửa câu chữ hiển thị", description: "Tiêu đề trang chỉnh sửa câu chữ." },
  "content.description": {
    value: "Tìm và chỉnh sửa những câu chữ người dùng nhìn thấy mà không cần sửa mã nguồn.",
    description: "Mô tả trang chỉnh sửa câu chữ.",
  },
  "content.searchPlaceholder": {
    value: "Ví dụ: đăng nhập, lưu thay đổi, chưa có dữ liệu",
    description: "Gợi ý tìm kiếm câu chữ hiển thị.",
  },
  "content.valuePlaceholder": {
    value: "Nhập nội dung hiển thị",
    description: "Gợi ý trong ô chỉnh sửa câu chữ.",
  },
  "content.active": { value: "Đang áp dụng", description: "Nhãn cho nội dung đang được sản phẩm sử dụng." },
  "content.save": { value: "Lưu câu chữ", description: "Nhãn nút lưu câu chữ." },
  "content.saving": { value: "Đang lưu thay đổi...", description: "Trạng thái đang lưu câu chữ." },
  "content.empty": {
    value: "Chưa tìm thấy câu chữ phù hợp.",
    description: "Thông báo khi tìm kiếm không có kết quả.",
  },
  "media.uploadTitle": { value: "Tải tư liệu mới", description: "Tiêu đề form tải tư liệu." },
  "media.uploadDescription": {
    value:
      "Ảnh tối đa 10MB, âm thanh tối đa 20MB, video tối đa 50MB. Hãy mô tả rõ nội dung để hỗ trợ khả năng tiếp cận.",
    description: "Hướng dẫn tải tư liệu.",
  },
  "media.altLabel": { value: "Mô tả nội dung tư liệu", description: "Nhãn mô tả tư liệu." },
  "media.altPlaceholder": {
    value: "Mô tả hình ảnh hoặc âm thanh",
    description: "Placeholder mô tả tư liệu.",
  },
  "media.upload": { value: "Tải lên", description: "Nhãn nút tải media." },
  "media.uploading": { value: "Đang tải...", description: "Nhãn khi tải media." },
  "media.uploadSuccess": {
    value: "Đã tải tư liệu lên thư viện",
    description: "Thông báo tải tư liệu thành công.",
  },
  "media.reviewOnly": {
    value: "Bạn có thể kiểm tra và duyệt tư liệu. Chỉ biên tập viên hoặc quản trị viên mới được tải tệp mới.",
    description: "Thông báo quyền tư liệu.",
  },
  "media.approve": { value: "Duyệt tư liệu", description: "Nhãn duyệt tư liệu." },
  "media.reject": { value: "Đánh dấu tư liệu không phù hợp", description: "Nhãn từ chối tư liệu." },
  "media.delete": { value: "Xóa tư liệu", description: "Nhãn xóa tư liệu." },
  "media.deleteConfirm": { value: "Xóa vĩnh viễn tư liệu này?", description: "Xác nhận xóa tư liệu." },
  "settings.title": { value: "Cấu hình hệ thống", description: "Tiêu đề quản lý cấu hình hệ thống." },
  "settings.jsonLabel": { value: "Giá trị", description: "Nhãn giá trị cấu hình." },
  "settings.jsonPlaceholder": { value: "Nhập giá trị", description: "Gợi ý nhập giá trị cấu hình." },
  "settings.save": { value: "Lưu", description: "Nhãn lưu cấu hình." },
  "settings.saving": { value: "Đang lưu...", description: "Nhãn khi lưu cấu hình." },
  "settings.saved": { value: "Đã lưu cấu hình hệ thống", description: "Thông báo lưu cấu hình." },
  "settings.createTitle": { value: "Thêm cấu hình mới", description: "Tiêu đề thêm cấu hình." },
  "settings.keyLabel": { value: "Mã cấu hình", description: "Nhãn kỹ thuật của cấu hình." },
  "settings.keyPlaceholder": { value: "Ví dụ: feature.enabled", description: "Placeholder mã cấu hình." },
  "settings.create": { value: "Thêm cấu hình", description: "Nhãn tạo cấu hình." },
  "world.createTitle": { value: "Thêm chủ đề nhiệm vụ", description: "Tiêu đề thêm chủ đề nhiệm vụ." },
  "world.slugLabel": { value: "Mã đường dẫn", description: "Nhãn mã đường dẫn chủ đề nhiệm vụ." },
  "world.titleLabel": { value: "Tên chủ đề", description: "Nhãn tên chủ đề nhiệm vụ." },
  "world.subtitleLabel": { value: "Câu giới thiệu ngắn", description: "Nhãn câu giới thiệu chủ đề." },
  "world.descriptionLabel": {
    value: "Mô tả cho phụ huynh và bé",
    description: "Nhãn mô tả chủ đề nhiệm vụ.",
  },
  "world.coverLabel": { value: "Ảnh bìa chủ đề", description: "Nhãn tải ảnh bìa cho chủ đề nhiệm vụ." },
  "world.sortOrderLabel": { value: "Vị trí trên bản đồ", description: "Nhãn thứ tự chủ đề." },
  "world.themeLabel": { value: "Màu chủ đề", description: "Nhãn màu chủ đề." },
  "world.statusLabel": { value: "Trạng thái hiển thị", description: "Nhãn trạng thái chủ đề." },
  "world.create": { value: "Thêm chủ đề", description: "Nhãn thêm chủ đề nhiệm vụ." },
  "world.creating": { value: "Đang tạo...", description: "Trạng thái đang thêm chủ đề." },
  "world.update": { value: "Lưu thay đổi", description: "Nhãn lưu thay đổi chủ đề." },
  "world.updating": { value: "Đang lưu...", description: "Trạng thái đang lưu chủ đề." },
  "world.createSuccess": { value: "Đã thêm chủ đề nhiệm vụ", description: "Thông báo thêm chủ đề nhiệm vụ." },
  "world.updateSuccess": {
    value: "Đã cập nhật chủ đề nhiệm vụ",
    description: "Thông báo cập nhật chủ đề nhiệm vụ.",
  },
});
